### ISSUE TITLE
Variables in Project Files cause resolution failure...

### ISSUE THREAD

**Issue by DynConcepts** [3F/MvsSln#34] opened 2020-12-14 12:38 UTC
Consider:

`  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
`

IF I simply load the solution, and then type to load the projects, "VSTargetsPath" seems to be empty as the project path resolves to "C:\"....

**Comment by 3F** [comment] 2020-12-14 20:42
Not sure what is exactly your problem here. Does this help to your issue https://github.com/3F/MvsSln/issues/32#issuecomment-717907520 ? or please full steps to reproduce. Thanks.

**Comment by DynConcepts** [comment] 2020-12-15 00:06
The linked issue [#32] covers the exact problem I was trying to explain. I will evaluate the solutions proposed there... If I have questions, I can post here (if you want) or on the #32 thread (at which point close this as resolved...

I am looking for solutions that have *minimum dependencies" (e.g. Visual Studio not Installed) so that the analysis code can run on the widest set of platforms - e.g. running the analysis of .vcxproj files, or old version "full framework" .csproj (perhaps from VS-2010 timeframe)  on an Ubuntu VM

**Comment by 3F** [comment] 2020-12-15 10:43
I close this as duplicate but feel free to continue here or there.

> I am looking for solutions that have *minimum dependencies" (e.g. Visual Studio not Installed)

[IeXod](https://github.com/3F/IeXod) will do this as you can see in planned MvsSln 3.0 because of the [same problems](https://github.com/3F/MvsSln/wiki/Advanced-Features#custom-msbuild-resolver):

> modern Microsoft.Build assemblies are much more closely integrated with Visual Studio and much more difficult to maintain independently (ie. without VS/dotnet sdk dependencies)

Today either try custom implementation for your case like [it was for DllExport in past](https://github.com/3F/DllExport/blob/e9b20af53dc84814f1bb94d4ef52c9605b94122e/Wizard/DxpIsolatedEnv.cs#L51) (actually today's DllExport project uses https://github.com/3F/hMSBuild but this is not your case at all) or anything from our wiki

**Closed by 3F** 2020-12-15 10:43 UTC
